### ISSUE TITLE
Installation Error: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by somejavadev** [floatinghotpot/cordova-httpd#49]
Hi,

I am getting the error below when trying to install the plugin in my ionic project.

TypeError: Cannot read property 'indexOf' of undefined
    at /home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:244:44
    at Array.forEach (native)
    at getEngines (/home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:223:13)
    at runInstall (/home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:285:22)
    at /home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:84:16
    at _fulfilled (/home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/home/xxxxx/.npm-packages/lib/node_modules/cordova/node_modules/q/q.js:108:17)

The command I ran was:

cordova plugin add https://github.com/floatinghotpot/cordova-httpd.git

My environment is as follows:

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.1.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.4 LTS 
Node Version: v0.12.7

I have had a look and it seems to fail on the following line in plugman:

/src/plugman/install.js:244:44 -> platformIndex = engine.platform.indexOf(platform);

I am not entirely sure why this is.

I have added the android platform to my project:

Installed platforms: android 4.1.1

I have used this plugin in the passed and I am not sure why this is currently occuring.

Perhaps you could assist.

Regards

**Comment by somejavadev** [comment]
I resolved this myself. I am not entirely sure why this would happen but the following fixed it for me. I thought It might be plugman itself and updated it to the latest, then I installed the cordova plugin again to make sure plugman could find the platform it was complaining about in the exception.

npm cache clean //Make sure it's not a caching issue.
npm install -g plugman //Update plugman to the latest version.

At this point plugman complained about a minimatch plugin which is using an older version

npm install -g minimatch@3.0.2 //Update the plugin which it was complaining about to the latest.
npm install -g cordova //install the cordova plugin again.

cordova plugin add https://github.com/floatinghotpot/cordova-httpd.git // Successful install.

Hope this helps anyone else having the same issue.
